dbc_overflow/config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    member do
        post 'upvote'
        post 'downvote'
      end
    resources :answers do
     member do
        post 'upvote'
        post 'downvote'
      end
    end
  end

  root 'questions#index'

end

dbc_overflow/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates_presence_of :content
end

dbc_overflow/app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  validates_presence_of :title
  validates_presence_of :content

end

dbc_overflow/app/controllers/answers_controller.rb
class AnswersController < ApplicationController

   def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    @answer.save
    if request.xhr?
      respond_to do |format|
        format.html
        format.js{render :create}
      end
    else
      redirect_to @question
    end
   end



    def upvote
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
    @answer.votes +=1
    @answer.save
    if request.xhr?
      respond_to do |format|
        format.html
        format.js{render :vote}
      end
    else
      redirect_to question_path(@question)
    end
  end

  def downvote
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
    @answer.votes -=1
    @answer.save
    if request.xhr?
      respond_to do |format|
        format.html
        format.js{render :vote}
      end
    else
      redirect_to question_path(@question)
    end
  end
private
    def answer_params
      params.require(:answer).permit(:content)
    end

end

dbc_overflow/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

dbc_overflow/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, except: [:index, :create, :new]
  respond_to :html, :js


  def index
    @question = Question.new
    @questions = Question.all
    headers["User-Agent"] = ENV['USERNAME']
    headers["Authorization"] = ENV['KEY']
    @response = HTTParty.get("https://api.github.com/zen", headers: headers)
    @response = "All's well that ends well" if @response.code != 200
  end

  def show
    # shows a specific question with all its answers
    @answer = Answer.new
  end

  def new
    render index
  end

   def create
    @question = Question.create(question_params)
    respond_to do |format|
      format.html
      format.js{render :create}
    end
   end

  def edit
  end

  def upvote
    @question.votes += 1
    @question.save
    respond_to do |format|
      format.html
      format.js{render :vote}
    end
  end

  def downvote
    @question.votes -= 1
    @question.save
     respond_to do |format|
      format.html
      format.js{render :vote}
    end
  end

  def update
    if @question.update(question_params)
      redirect_to question_path(@question)
    else
      render edit
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      if request.xhr?
        format.html
        format.js{render :remove}
      else
        format.html {redirect_to questions_path}
      end
    end
  end

  private
    def question_params
      params.require(:question).permit(:title, :content, :votes)
    end


    def find_question
      @question = Question.find(params[:id])
    end
end

dbc_overflow/app/helpers/answers_helper.rb
module AnswersHelper
end

dbc_overflow/app/helpers/application_helper.rb
module ApplicationHelper
end

dbc_overflow/app/helpers/questions_helper.rb
require 'httparty'

module QuestionsHelper
end

module API
  class Client
    include HTTParty
    base_uri = "http://api.github.com"
    headers["User-Agent"] = "franjohn21"

    def zen
      response = self.class.get('/zen')
      return response
    end

  end
end

dbc_overflow/app/views/answers/_form.html.erb
<%= form_for [@question, @answer], remote: true do |f| %>
  Full Answer: <%= f.text_area :content %> <br />
  <%= f.submit %>
<% end %>

dbc_overflow/app/views/answers/_list.html.erb
<li><%= link_to content_tag(:i,nil, :class=>"fa fa-chevron-up vote_arrow"),upvote_question_answer_path(@question, answer), method: :post, remote: true %>
<%= link_to content_tag(:i,nil, :class=>"fa fa-chevron-down vote_arrow"), downvote_question_answer_path(@question, answer), method: :post, remote: true %>  <span id="answer-<%=answer.id%>"><%= answer.votes %> </span> -- <%=  answer.content %>
</li>

dbc_overflow/app/views/answers/create.js.erb
$(".answers_list").append("<%= j render partial: 'list', locals: {answer: @answer} %>")

dbc_overflow/app/views/answers/vote.js.erb
$("#answer-<%=@answer.id%>").text(<%= @answer.votes %>)

dbc_overflow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

dbc_overflow/app/views/questions/_form.html.erb
<%= form_for(@question, remote: true) do |f| %>
  Title: <%= f.text_field :title %> <br />
  Full description: <%= f.text_area :content %> <br />
  <%= f.submit %>
<% end %>

dbc_overflow/app/views/questions/_list.html.erb
<li><span id="question-<%= question.id %>"> <%= question.votes %> </span><%= link_to content_tag(:i,nil, :class=>"fa fa-chevron-up vote_arrow"), upvote_question_path(question), method: :post, remote: true %>

<%= link_to content_tag(:i,nil, :class=>"fa fa-chevron-down vote_arrow"), downvote_question_path(question), method: :post, remote: true %>  <%= link_to question.title, question_path(question)%>


<%= link_to 'Destroy', question_path(question), method: :delete, remote: true %>
</li>

dbc_overflow/app/views/questions/create.js.erb
$(".question_list").append("<%= j render partial: 'list', locals: {question: @question} %>")

dbc_overflow/app/views/questions/edit.html.erb
<h1>Edit your question</h1>
<%= render 'form' %>

dbc_overflow/app/views/questions/index.html.erb
<h3>Create New Question   </h3>
<%= render 'form' %>
<h3>All questions</h3>
<ul class="question_list">
<% @questions.order('created_at').each do |question| %>
<%= render partial: "list", locals: {question: question} %>
<% end %>
</ul>
<div id='quote'>
  <h1><%= @response %></h1>
</div>

dbc_overflow/app/views/questions/remove.js.erb
$("#question-<%= @question.id %>").parent().remove();

dbc_overflow/app/views/questions/show.html.erb
<h3><%= link_to content_tag(:i,nil, :class=>"fa fa-chevron-up vote_arrow"), upvote_question_path(@question), method: :post, remote: true %>

<%= link_to content_tag(:i,nil, :class=>"fa fa-chevron-down vote_arrow"), downvote_question_path(@question), method: :post, remote: true %><span id="question-<%= @question.id %>"> <%= @question.votes %></span> -- <%= @question.title %></h3>
<%= @question.content %>

 </span>

<h3>Answer this question</h3>
<%= render 'answers/form' %>
<h3>Answers</h3>
<ul class="answers_list">
  <% @question.answers.order('created_at').each do |answer| %>
    <%= render partial: 'answers/list', locals: {answer: answer}%>
  <% end %>
</ul>
<%= link_to 'Destroy', question_path(@question), method: :delete, data: {confirm: 'Are you sure?'} %>

dbc_overflow/app/views/questions/vote.js.erb
$("#question-<%= @question.id %>").text(" <%=@question.votes%> ")